config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}

  get 'my_stores', to: 'my_stores#index'

  get 'questions', to: 'infos#questions'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :stores do
    get :admin, on: :member
    resources :products, only: %i[new create]
    resources :reviews, only: %i[new create update edit destroy]
  end

  resources :products, only: %i[index show edit update destroy]
  resources :carts, only: %i[create edit update destroy]
    get 'cart', to: 'carts#show'
  resources :cart_items, only: %i[create destroy update]
  resources :product_categories, only: %i[create destroy]
  # resources :reviews, only: :destroy
  resources :orders, only: %i[show index create update]
  resources :categories, only: :show


end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true,  length: { in: 2..30 }
  validates :address, presence: true
  validates :city, presence: true,  length: { in: 2..30 }
  validates :email, presence: true, format: { with: /\A[\w|.|-]+@[\w|-]+\.\w+\z/ }
  validates :phone, presence: true, length: { minimum: 9 } #numericality: { only_integer: true }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/stores_controller.rb
require_relative "../models/user"
require_relative "../models/store"
class StoresController < ApplicationController

  # before_action :set_user, only: [:new, :create]
  before_action :set_store, only: [:show, :edit, :update, :destroy, :admin]

  def index
    @pagy, stores = pagy(policy_scope(Store), items: 6)
    @stores = stores.geocoded # trae stores´s que tengan latitude y longitude obtenidas con la gema
    @markers = @stores.geocoded.map do |store|
      {
        lat: store.latitude,
        lng: store.longitude,
        info_window: render_to_string(partial: "info_index",
        locals: { store: store })
      }
    end
  end

  def show
    @cart_item = current_cart.cart_items.new
    admin
    @review = Review.new

    if @store.reviews.blank?
      @average_review = 0
    else
      @average_review = @store.reviews.average(:rating).round(2)
    end
    @markers = [
      {
        id: @store.id,
        lat: @store.latitude,
        lng: @store.longitude,
        info_window: render_to_string(partial: "info_window",
        locals: { store: @store })
      }
    ]

  end

  def new
      @store = Store.new
      authorize @store
  end

  def create
    @store = Store.new(store_params)
    @store.user = current_user
    authorize @store

    # Si la tienda se crea con éxito será redireccionado a su show,
    #   en caso contrario será redireccionado a las tiendas.
    if @store.save
      if !current_user.seller
        current_user.make_it_a_seller!
        current_user.save
      end
      @store.save
      redirect_to store_path(@store), notice: "Su tienda fue creada con éxito."
    else
      render :new
    end
  end

  def edit
  end

  def update
    @store.update(store_params)
    redirect_to store_path(@store)
  end

  def destroy
    # Si la tienda se elimina, el usuario será redireccionado a su perfil.
    @store.destroy
    @stores_number = current_user.stores.size
    if @stores_number == 0
      current_user.make_it_a_not_seller!
      current_user.save
    end
    # LA RUTA ESTABLECIDA ES PROVISORIA,SE RECOMIENDA redirect_to user_path(@user).
    redirect_to stores_path
  end

  def admin
    @pagy, @products = pagy(@store.products,items: 12)
  end

private

  #def set_user
    # @user = User.find(params[:user_id])
  # end


  def set_store
    @store = Store.find(params[:id])
    authorize @store
  end

  def store_params
    params.require(:store).permit(:name, :address, :city, :email, :phone, photos: [])
  end
end

app/views/stores/_form.html.erb
<div class="container d-flex flex-column align-items-center">
  <%= simple_form_for @store do |f| %>
    <div class="new-store-form d-flex flex-column align-items-start">
      <%= f.input :name, input_html: { class: "inputs-store" },
      label: "Nombre de la tienda" %>
      <%= f.input :address, input_html: { class: "inputs-store" },
      label:"Dirección" %>
      <%= f.input :city, input_html: { class: "inputs-store" }, label: "Ciudad" %>
      <%= f.input :email, input_html: { class: "inputs-store" } %>
      <%= f.input :phone, input_html: { class: "inputs-store" },
      label: "Teléfono"%>
      <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Foto de la tienda", class: "w-100" %>
    </div>
    <div class="dropdown-divider"></div>
    <div class="text-center">
      <%= f.button :submit, "Guardar", class: "btn boton-primario mb-5" %>
      <%= link_to  "Volver", request.referrer, class: "btn boton-primario mb-5" %>
    </div>
  <% end %>
</div>

app/views/stores/_info_index.html.erb
<h5><%= store.name %></h5>
<h5>Ciudad: <%= store.city %></h5>
<%= link_to  "Más detalles",store_path(store), class: "btn boton-primario" %>

app/views/stores/_info_window.html.erb
  <h3> <%= store.name %> </h3>
  <h4>Dirección: <%= store.address %></h4>

app/views/stores/admin.html.erb
<% if @products.size > 0 %>
<div class="container">
  <div class="container px-1 py-3">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <h1>Mis productos</h1>
      </div>
      <div class="col-md-3">
      <%= link_to  "Agregar producto", new_store_product_path(@store.id), class: "btn boton-primario" %>
      </div>
    </div>
  </div>
  <div class="container p-1">
    <% @products.order(id: :asc).each do |product| %>
      <div class="d-flex align-items-center">
        <div class="col-md-3 m-1">
          <% if product.photos.attached? %>
            <% product.photos.first(1).each do |photo| %>
              <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill %>
            <% end %>
          <% else %>
            <%= image_tag "no_product_image.png", height: 150, width: 200, crop: :fill %>
          <% end %>
        </div>
        <div class="col-md-5 m-1">
          <%= link_to(product_path(product)) do%>
            <p class="product-name"><%= product.name %></h3>
          <% end %>
          <p class="product-description"><%= product.description%></p>
        </div>
        <div class="col-md-2 m-1">
            <% unless product.discount %>
              <p class="">Precio normal</p>
              <p class="product-price">$<%= product.price%></p>
            <% else %>
              <p class="product-price-discount">Precio normal</p>
              <p class="product-price-discount">$<%= product.price%></p>
              <p class="">Precio oferta</p>
              <p class="product-price discount">$<%= product.discount_price%></p>
            <% end %>
            <% unless product.active %>
              <p><%= "Producto no disponible" %></p>
            <% end %>
        </div>
        <div class="col-md-2 m-1">
            <%= link_to edit_product_path(product.id), class: "" do %>
              <i class="fas fa-pen danger"></i>
            <% end %>
            <%= link_to product_path(product.id), method: :delete, data: { confirm: "Estás seguro?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
        </div>
      </div>
    <% end %>
    <% if policy(@store).edit? %>
      <%= link_to  "Volver", store_path(@store), class:"btn boton-primario" %>
    <% end %>
    <div class="pagination m-2 p-2 align-self-center ">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>

  </div>
</div>
<% else %>
  <div class="empty-cart d-flex flex-column align-items-center justify-content-center">
    <%= image_tag "carrito.png", alt: "Carrito de compras", class: "img-carrito" %>
    <h2>¡Aún no tienes productos!</h2>
    <p class="continuar-compra">Agrega ahora productos a tu tienda</p>
    <%= link_to  "Agregar producto", new_store_product_path(@store.id), class: "btn boton-primario" %>
  </div>
<% end -%>

app/views/stores/edit.html.erb
<h1 class ="title-cart text-center">Editar Tienda</h1>
  <div class="edit-store-form">
    <%= render "form", store: @store %>
  </div>

app/views/stores/index.html.erb
<div class="container-fluid ">
  <h1 class ="title-cart text-center">Tiendas</h1>
  <div class="row m-5">

    <div class="col-md-8 d-flex flex-column ">
      <div class="index-stores mb-4">
        <% @stores.shuffle.each do |store| %>
          <%= link_to(store_path(store)) do %>
            <% if store.photos.attached? %>
              <% store.photos.each do |photo| %>
              <div class="store py-5 pl-4"style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(<%= cl_image_path photo.key,crop: :fill %>)">
                <h3 class="store-name"><%= store.name %> </h3>
                <label class="rating-label"><!-- <strong>El rating promedio de la tienda es <%= (store.reviews.sum(:rating) / store.reviews.count).round(2) %></strong> -->
                  <div class="stars-content d-flex">
                    <input class="rating" max="5" readonly step="0.01" style="--fill:orange;--value:<%= (store.reviews.sum(:rating) / store.reviews.count).round(2) %>" type="range" value=<%= (store.reviews.sum(:rating) / store.reviews.count).round(2) %>>
                  </div>
                </label>
                <p><%= store.address %></p>
                <p> <i class="fas fa-phone-alt call-icon mr-2"></i> <%= store.phone %> </p>
              </div>
              <% end %>
            <% else %>
              <div class="store default-image py-5 pl-4">
                <h3 class="store-name"> <%= store.name %> </h3>
                <label class="rating-label"><!-- <strong>El rating promedio de la tienda es <%= (store.reviews.sum(:rating) / store.reviews.count).round(2) %></strong> -->
                  <div class="stars-content d-flex">
                    <input class="rating" max="5" readonly step="0.01" style="--fill:orange;--value:<%= (store.reviews.sum(:rating) / store.reviews.count).round(2) %>" type="range" value=<%= (store.reviews.sum(:rating) / store.reviews.count).round(2) %>>
                  </div>
                </label>
                <p><%= store.address %></p>
                <p><i class="fas fa-phone-alt call-icon mr-2"></i> <%= store.phone %> </p>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

        <div class="pagination m-2 p-2 align-self-center">
          <%== pagy_bootstrap_nav(@pagy)  if @pagy.pages > 1 %>
        </div>

    </div>

    <div class="col-md-4">
      <div id="map"
      style="width: 100%; height: 75vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>

  </div>
</div>

app/views/stores/new.html.erb
<h1 class="card-title text-center mt-5">Crear Tienda</h1>
<div class="new-store-form mt-5">
  <%= render "form", store: @store %>
</div>

app/views/stores/show.html.erb
<div class="container-fluid">
  <div class="row m-5">
    <div class="col-9 d-flex flex-column justify-content-start">
      <div class="card-store d-flex">
        <% if @store.photos.count > 0 %>
          <div class="image-store">
            <% @store.photos.each do |photo| %>
               <%= cl_image_tag photo.key, height: 250, width: 250, crop: :fill %>
            <% end %>
          </div>
        <% else %>
          <div class="logo-store-image d-flex justify-content-center align-items-center align-self-center text-center bold px-2">
            <p> <%= @store.name %> </p>
          </div>
        <% end -%>

        <div class="content-store py-4 pl-4">
          <h1 class="store-name bold"><%= @store.name %></h1>
          <p><%= @store.address %> </p>
          <p><%= @store.city %> </p>
          <p><%= @store.phone%> </p>
          <p><%= @store.email %> </p>

          <% if @average_review != 0 %>
            <label class="rating-label mt-2">
              <div class="stars-content d-flex align-items-center">
                <input class="rating_avg mr-2" max="5" readonly step="0.01" style="--fill:orange;--value:<%= (@store.reviews.sum(:rating) / @store.reviews.count).round(2) %>" type="range" value=<%= (@store.reviews.sum(:rating) / @store.reviews.count).round(2) %>>
                <p class="comment mr-2 bold"><%= @average_review %></p>
                <span id="base-comment" class="comment bold">(<%= @store.reviews.count %> comentarios)</span>
              </div>
            </label>
          <% else %>
            <br>
          <% end %>


          <% if policy(@store).edit? %>
            <%= link_to  "Eliminar tienda", store_path, class: "btn btn-danger mr-2", method: :delete , data: { confirm: "Estás seguro?" } %>
            <%= link_to  "Editar tienda", edit_store_path, class: "btn boton-primario" %>
          <% else %>
            <%= link_to  "Contactar al Productor", "https://wa.me/56#{@store.phone}?text=Hola,%20ví%20tu%20tienda%20en%20Demizona%20y%20quisiera%20hacerte%20una%20pregunta", target: "_blank", class: "btn boton-primario"%>
          <% end %>
        </div>
      </div>

      <div class="d-flex flex-column mt-3">
        <div class="d-flex justify-content-between align-items-center">
          <p class="bold"> <%= @store.products.count %> Productos</p>
          <% if policy(@store).edit? %>
            <%= link_to "Administrar mis productos", admin_store_path, class: "btn boton-primario" %>
          <% end %>
        </div>
        <div class="products-store mt-5 justify-content-start mx-4">
          <%= render "/products/product_card" %>
        </div>
      </div>

  <div class="pagination m-2 p-2 align-self-center ">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
  </div>


      <div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <section id="reviews-section-th">
          <ol id="reviews">
            <%= render @store.reviews.last(3) %>
          </ol>
        </section>

        <section id="reviews-section">
          <ol id="reviews">
            <%= render @store.reviews %>
          </ol>
        </section>
        <button id="btn-review" class="btn boton-primario">Mostrar todas las reseñas</button>
        <div class="action-stores">
          <!--<%= link_to "Añadir Reseña", new_store_review_path(@store) %> -->
          <!--<%= link_to  "Todas las tiendas", stores_path, class: "btn btn-success" %>-->
        </div>
      </div>

    </div>

    <div class="col-3 d-grid" id="block-right">
      <div class="map-review">
        <div id="map" style="width: 20vw; height: 40vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        <div class="create-review mt-5">
          <div id="new-review">
            <h3>Valora nuestra Tienda</h3>
            <%= render "reviews/form" %>
          </div>
          <div id="new-review-save">
            <h3>Gracias por su comentario!</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>