config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}

  get 'my_stores', to: 'my_stores#index'

  get 'questions', to: 'infos#questions'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :stores do
    get :admin, on: :member
    resources :products, only: %i[new create]
    resources :reviews, only: %i[new create update edit destroy]
  end

  resources :products, only: %i[index show edit update destroy]
  resources :carts, only: %i[create edit update destroy]
    get 'cart', to: 'carts#show'
  resources :cart_items, only: %i[create destroy update]
  resources :product_categories, only: %i[create destroy]
  # resources :reviews, only: :destroy
  resources :orders, only: %i[show index create update]
  resources :categories, only: :show


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="d-flex justify-content-between py-4">
        <div class="feature mr-3">
          <%= image_tag "rocket.png", alt: "Cohete", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title">Envíos gratis</p>
            <p class="feature-subtitle">En compras mayores a $50.000</p>
          </div>
        </div>

        <div class="feature mr-3">
          <%= image_tag "devolucion.png", alt: "Devolución", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title">Devoluciones</p>
            <p class="feature-subtitle">Antes de las 24 horas</p>
          </div>
        </div>

        <div class="feature mr-3">
          <%= image_tag "seguridad.png", alt: "Seguridad", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title">Pagos 100% Seguros</p>
            <p class="feature-subtitle">Pagos seguros garantizados</p>
          </div>
        </div>

        <div class="feature mr-3">
          <%= image_tag "support.png", alt: "Soporte", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title">Soporte 24/7</p>
            <p class="feature-subtitle">Donde sea y a cualquier horario</p>
          </div>
        </div>

        <div class="feature mr-3">
          <%= image_tag "tag.png", alt: "Etiqueta", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title">Ofertas diarios</p>
            <p class="feature-subtitle">Descuentos hasta 70%</p>
          </div>
        </div>
    </div>
    <div class="footer-divider"></div>
    <div class="d-flex py-5 mx-4 justify-content-between">
      <div class="info-footer">
        <p class="title-links mb-2">Demizona - Tu mayor tienda online</p>
        <p class="mb-3 footer-text">Encuentra nuestros proveedores certificados, entregándole valor al productor local, permitiendo establecer un contacto directo entre cliente y usuario.</p>

        <div class="d-flex align-items-center">
          <i class="fas fa-phone-alt call-icon mr-2"></i>
          <p>Llamadas 24/7:</p>
        </div>
        <div class="d-flex flex-column mt-2">
          <a href="tel:+56912345678" class="tel-link ml-3">+56 (9) 1234 5678</a>
          <a href="mailto:soporte@demizona.cl" class="ml-3 email-link mt-2">soporte@demizona.cl</a>
        </div>
      </div>
      <div class="links d-flex flex-column">
        <p class="title-links mb-2">Links de interés</p>
        <%= link_to "Preguntas Frecuentes", questions_path, class: "footer-link" , target: "_blank"%>
        <%= link_to "Sobre nosotros","#" , class: "footer-link" %>
        <%= link_to "Contáctanos", "#", class: "footer-link" %>
        <%= link_to "Politica de privacidad", "#", class: "footer-link" %>
      </div>
      <div class="links d-flex flex-column">
        <p class="title-links mb-2">Centro de Ayuda</p>
        <%= link_to "Pagos", "#", class: "footer-link" %>
        <%= link_to "Envíos", "#", class: "footer-link" %>
        <%= link_to "Devoluciones y cambios", "#", class: "footer-link" %>
      </div>
      <div class="links d-flex flex-column">
        <p class="title-links mb-2">Negocios Demizona</p>
        <%= link_to "Vende en Demizona", "#", class: "footer-link" %>
        <%= link_to "Nuestras tiendas", "#", class: "footer-link" %>
        <%= link_to "Promocionate con nosotros", "#", class: "footer-link" %>
      </div>
    </div>
    <div class="footer-divider"></div>
    <p class="py-3 footer-text">© 2021 <strong>Demizona.</strong> Todos los derechos reservados.</p>
  </div>
</div>

app/views/shared/_login_form.html.erb
<div class="modal fade bd-example-modal-lg" id="myModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="login-modal flex-row">
      <div class="modal-img">
        <%= image_tag "login.jpg", class:"login-img" %>
      </div>
      <div class="login-formulario">
        <div class="login-close">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <ul class="nav mb-2 align-self" data-tabs="tabs">
            <li id="tab1" class="">
              <a class="modal-title mr-4 active" href="#Login" data-toggle="tab">Inicia Sesión</a>
            </li>
            <li id="tab2">
              <a class="modal-title" href="#Signup" data-toggle="tab">Regístrate</a>
            </li>
          </ul>
          <div class="border-bottom mb-3"></div>
          <div class="tab-content">
            <div class="tab-pane active" id="Login">
              <p class="login-title">Ingresa a tu cuenta</p>
              <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true) do |f| %>
                <div class="login-margin-bottom">
                  <%= f.input :email,
                      required: false,
                      autofocus: true,
                      placeholder: "correo@ejemplo.com",
                      input_html: { autocomplete: "email", class: "inputs login-inputs" } %>
                  <%= f.input :password,
                      required: false,
                      label: "Contraseña",
                      placeholder: "••••••••••",
                      input_html: { autocomplete: "current-password", class: "inputs login-inputs" } %>
                  <%= f.input :remember_me,
                      label: "Recuérdame",
                      as: :boolean if devise_mapping.rememberable? %>
                </div>
                <div class="d-flex flex-column align-items-center mb-3">
                  <%= f.button :submit, "Iniciar Sesión", class: "btn boton-primario boton-login" %>
                  <%= link_to "¿Olvidaste tu contraseña?", new_user_password_path, class: "mt-2 bold text-small"  %>
                </div>
              <% end %>
            </div>
            <div class="tab-pane" id="Signup">
              <p class="login-title">Crea tu cuenta</p>
              <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= f.error_notification %>

                <div class="signup-margin-bottom">
                  <div class="d-flex">
                    <%= f.input :name,
                                required: true,
                                label: "Nombre",
                                placeholder: "Pedro",
                                input_html: { autocomplete: "name", class: "inputs signup-inputs mr-1" } %>
                    <%= f.input :last_name,
                                required: true,
                                label: "Apellidos",
                                placeholder: "Muñoz Saavedra",
                                input_html: { autocomplete: "last-name", class: "inputs signup-inputs" } %>
                  </div>
                  <%= f.input :email,
                              required: true,
                              autofocus: true,
                              placeholder: "correo@ejemplo.com",
                              input_html: { autocomplete: "email", class: "inputs email-inputs" }%>
                  <div class="d-flex">
                    <%= f.input :password,
                                required: true,
                                label: "Contraseña",
                                placeholder: "••••••••••",
                                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                input_html: { autocomplete: "new-password", class: "inputs signup-inputs mr-1" } %>
                    <%= f.input :password_confirmation,
                                required: true,
                                label: "Confirmar contraseña",
                                placeholder: "••••••••••",
                                input_html: { autocomplete: "new-password", class: "inputs signup-inputs" } %>
                  </div>

                  <div class="d-flex">
                  <%= f.input :address,
                              required: true,
                              label: "Dirección",
                              placeholder: "Av. Salgado 1234, Purén",
                              input_html: { autocomplete: "address", class: "inputs signup-inputs mr-1" } %>
                  <%= f.input :phone,
                              required: true,
                              label: "Teléfono",
                              placeholder: "+56912345678",
                              input_html: { autocomplete: "phone", class: "inputs signup-inputs" } %>
                  </div>
                </div>
                <div class="d-flex flex-column align-items-center mb-3">
                  <%= f.button :submit, "Regístrate", class: "btn boton-primario boton-login" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>


    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
  <div class="navbar navbar-expand-md navbar-light navbar-lewagon">
      <%= link_to root_path, class: "d-flex align-items-center flex-fill" do %>
        <%= image_tag "Zana.png" , class: "logo mx-2" %>
        <p class="logo-title">Demizona</p>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="search-center">
        <% if @q.present? %>

            <%= search_form_for @q do |f| %>
              <div class="d-flex search">
                <%= f.search_field :name_cont, placeholder: "Estoy buscando...", class: " search-bar" %>
                <%= f.submit "Buscar", class: "btn search-button"%>
              </div>
            <% end -%>
        <% end %>
      </div>




    <!-- <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form> -->

    <div class="collapse navbar-collapse justify-content-sm-between" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto align-items-center">
        <% if user_signed_in? %>
          <!-- <li class="nav-item active mx-4">
            <%= link_to "#", class: "d-flex align-items-center" do %>
              <i class="fas fa-map-marker-alt"></i>
              <p class="user-name ml-1"><%= current_user.address %></p>
            <% end %>
          </li> -->
          <li class="nav-item active d-flex mx-4 dropdown no-decoration">
              <%= link_to "#", class: "no-decoration", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
                <div class="d-flex align-items-center">
                  <div class="mr-2">
                    <i class="fas fa-user fa-lg"></i>
                  </div>
                  <div class="d-flex flex-column over-title">
                    <p class="sobre-title">Hola!</p>
                    <p class="user-name"><%= current_user.name %></p>
                  </div>
                </div>
              <% end %>
              <% if current_user.seller %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <p class="dropdown-title pl-4 py-3">Mi cuenta</p>
                  <%= link_to "Mis pedidos", orders_path, class: "dropdown-item" %>
                  <%= link_to "Editar mi perfil", edit_user_registration_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <p class="dropdown-title pl-4 py-3">Vendedor</p>
                  <%= link_to "Mis tiendas", my_stores_path, class: "dropdown-item" %>
                  <%= link_to  "Crear tienda", new_store_path(@store), class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              <% else %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <p class="dropdown-title pl-4 py-3">Mi cuenta</p>
                  <%= link_to "Mis pedidos", orders_path, class: "dropdown-item" %>
                  <%= link_to "Editar mi perfil", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Quiero ser vendedor", new_store_path(@store), class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              <% end -%>
          </li>
          <li class="nav-item d-flex mx-4">
            <%= link_to "/cart" do %>
                <div class="d-flex align-items-center">
                  <div class="mr-2">
                    <i class="fas fa-shopping-cart fa-lg"></i>
                  </div>
                  <div class="d-flex flex-column over-title">
                    <p class="sobre-title">Tu carrito</p>
                    <div id="cart">
                      <%= render 'carts/cart' %>
                    </div>
                  </div>
                </div>
              <% end %>
          </li>

        <% else %>
          <li class="nav-item d-flex align-items-center">
            <%= link_to 'Inicia Sesión o Regístrate', "", data: {toggle: "modal", target: ".bd-example-modal-lg"}, class: "mx-3 user-name" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>
  <%= render 'shared/login_form' %>