config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}

  get 'my_stores', to: 'my_stores#index'

  get 'questions', to: 'infos#questions'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :stores do
    get :admin, on: :member
    resources :products, only: %i[new create]
    resources :reviews, only: %i[new create update edit destroy]
  end

  resources :products, only: %i[index show edit update destroy]
  resources :carts, only: %i[create edit update destroy]
    get 'cart', to: 'carts#show'
  resources :cart_items, only: %i[create destroy update]
  resources :product_categories, only: %i[create destroy]
  # resources :reviews, only: :destroy
  resources :orders, only: %i[show index create update]
  resources :categories, only: :show


end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  has_many :orders, dependent: :destroy

  before_save :set_total_price

  def total_price
    cart_items.collect do |cart_item|
      if cart_item.valid?
        cart_item.item_price * cart_item.quantity
      else
        0
      end
    end.sum
  end

  private

  def set_total_price
    self[:total_price] = total_price
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart_items = current_cart.cart_items
    @order = Order.new
    authorize current_cart
  end

end

app/views/carts/_cart.html.erb
<p class="price"> <%="$#{current_cart.total_price}" %> </p>

app/views/carts/_cart_items.html.erb
<% if @cart_items.size > 0 %>
<div class="container">
  <h1 class="text-center title-cart">Carrito de Compras</h1>
  <div class="d-flex justify-content-center align-items-center">
    <div class="mx-4">
      <div class="carrito-table">
        <table class="cart-item-table">
          <tr class="table-header">
            <th class="text-center py-2 title-header">Productos</th>
            <th class="px-5 py-2 title-header">Precio</th>
            <th class="px-5 py-2 title-header">Cantidad</th>
            <th class="px-4 py-2 title-header"></th>
            <th class="px-5 py-2 title-header">Total</th>
            <th class="px-4 py-2 title-header"></th>
          </tr>
        <% @cart_items.order(id: :desc).each_with_index do |item, index| %>
          <tr class="table-divider">
            <td class="py-5">
              <div class="d-flex align-items-center px-3">
                <% if item.product.photos.attached? %>
                  <% item.product.photos.first(1).each do |photo| %>
                    <%= cl_image_tag photo.key, alt: item.product.name, class: "item-img" %>
                  <% end %>
                <% else %>
                  <%= image_tag "no_product_image.png", alt: "item.product.name", class: "item-img" %>
                <% end %>
                <div class="d-flex flex-column pl-4">
                  <p class="item-name"><%= item.product.name %></p>
                  <p class="detail-item">Vendido por <span><%= item.product.store.name %></span></p>
                </div>
              </div>
            </td>
            <td class="text-center">
              <% if item.product.discount %>
                $ <%= item.product.discount_price %>
              <% else %>
                $<%= item.product.price %>
              <% end -%>
            </td>
            <td class="text-center">
              <%= simple_form_for item, url: cart_item_path(item.id), remote: true do |f| %>
                <div class="d-flex align-items-center">
                  <%= f.hidden_field :product_id, value: item.product.id %>
                  <%= f.button :button, "-", class: "signo-btn minus", onclick: "if (document.getElementById('#{item.product.id}').value > 0) { document.getElementById('#{item.product.id}').value = parseInt(document.getElementById('#{item.product.id}').value) - 1 }; return false" %>
                  <%= f.number_field :quantity, value: item.quantity.to_i, class: "text-center quantity-product-cart", id: item.product.id %>
                  <%= f.button :button, "+", class: "signo-btn plus", onclick: "document.getElementById('#{item.product.id}').value = parseInt(document.getElementById('#{item.product.id}').value) + 1; return false" %>
                </div>
            </td>
            <td>
                <%= button_tag type: 'submit', class: "btn", remote: true do %>
                  <i class="fas fa-sync-alt"></i>
                <% end %>
              <% end %>
            </td>
            <td class="text-center">$<%= item.total %></td>
            <td>
              <%= link_to item, method: :delete, remote: true, class: "" do %>
                <i class="fas fa-trash-alt"></i>
              <% end -%>
            </td>
          </tr>
        <% end %>
        </table>
      </div>
      <%= link_to root_path, class: "d-flex align-items-center btn boton-terciario-icon btn-icon-size my-5" do %>
        <i class="fas fa-arrow-left fa-xs ml-2"></i>
        <p class="boton-title"><%= "Continuar comprando" %></p>
      <% end -%>
    </div>
    <div class="align-self-start">
      <div class="mb-3">
        <table class="subtotal-table">
          <tr>
            <th class="px-4 py-4">Subtotal</th>
            <th class="px-4 py-4">$<%= current_cart.total_price %></th>
          </tr>
          <tr>
            <td class="px-4">Envío Gratis a</td>
          </tr>
          <tr>
            <td class="px-4 pb-3"><%= current_user.address %></td>
          </tr>
          <tr>
            <td class="px-4 py-3 total-cart-title">TOTAL</td>
            <td class="px-4 py-3 price-cart">$<%= current_cart.total_price %></td>
          </tr>
        </table>
      </div>
      <%= link_to "Pagar", orders_path, method: :post, class: "d-flex align-items-center justify-content-center btn boton-primario"%>
    </div>
  </div>
</div>
<% else %>
  <div class="empty-cart d-flex flex-column align-items-center justify-content-center">
    <%= image_tag "carrito.png", alt: "Carrito de compras", class: "img-carrito" %>
    <h2>Tu Carrito está vacío</h2>
    <p class="continuar-compra">¿Quieres continuar con tu compra?</p>
    <%= link_to "Volver a Inicio", root_path, class: "btn boton-primario"  %>
  </div>
<% end -%>

app/views/carts/show.html.erb
<%= javascript_pack_tag "show_cart" %>
<div id="cart-item">
  <%= render 'cart_items' %>
</div>