config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}

  get 'my_stores', to: 'my_stores#index'

  get 'questions', to: 'infos#questions'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :stores do
    get :admin, on: :member
    resources :products, only: %i[new create]
    resources :reviews, only: %i[new create update edit destroy]
  end

  resources :products, only: %i[index show edit update destroy]
  resources :carts, only: %i[create edit update destroy]
    get 'cart', to: 'carts#show'
  resources :cart_items, only: %i[create destroy update]
  resources :product_categories, only: %i[create destroy]
  # resources :reviews, only: :destroy
  resources :orders, only: %i[show index create update]
  resources :categories, only: :show


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  has_many_attached :photos

  validates :name, presence: true, length: { in: 2..30 }
  validates :description, length: { maximum: 1000 }
  validates :price, presence: true
  validates :sku, presence: true, uniqueness: true

end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
  end

  def edit    
  end

  def update
    @product.update(product_params)
  end

  def destroy
    @product.destroy
  end

private

  def set_product
    @product = Product.find(params[:id])
  end

  def products_params
    params.require(:params).permit(:name, :description, :price, :active)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :find_store, only: [:new, :create]

  def index
    products = policy_scope(Product)
    if params[:q]
      @pagy, @products = pagy(@q.result(distinct: true), items: 25)
      @q = Product.ransack(params[:q])
    else
      @pagy, @products = pagy(policy_scope(Product), items: 25)
    end
    @cart_item = current_cart.cart_items.new
  end

  def show
    @cart_item = current_cart.cart_items.new
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.store = @store
    @product.category_ids = params[:product][:category_ids]

    if @product.save
      redirect_to admin_store_path(@product.store)
    else
      flash[:alert] = "Algo no funcionó correctamente."
      render :new
    end
    authorize @product
  end

  def edit
  end

  def update
    if @product.update(product_params)
      @product.category_ids = params[:product][:category_ids]
      redirect_to admin_store_path(@product.store)
      flash[:notice] = "El producto ha sido actualizado con éxito."
    else
      flash[:alert] = "Algo no funcionó correctamente."
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to admin_store_path(@product.store)
      flash[:notice] = "El producto ha sido eliminado."
    else
      redirect_to admin_store_path(@product.store)
      flash[:alert] = "Algo no funcionó correctamente."
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def product_params
    params.require(:product).permit(:name, :description, :sku, :price, :discount_price, :active, :featured, :unit_type, :quantity_stock, :discount, :category_ids, photos: [])
  end

  def find_store
    @store = Store.find(params[:store_id])
  end
end

app/views/products/_form.html.erb
<div class="container d-flex flex-column align-items-center">
  <%= simple_form_for [@store, @product] do |f| %>
    <div class="new-product-form d-flex flex-column align-items-start">
    <%= f.input :name, input_html: { class: "inputs-product" },
    label: "Nombre del producto" %>
    <%= f.input :description, input_html: { class: "inputs-product" },
    label: "Descripción" %>
    <%= f.input :sku, input_html: { class: "inputs-product" },
    label: "SKU" %>
    <%= f.input :price, input_html: { class: "inputs-product" },
    label: "Precio normal" %>
    <%= f.input :discount_price, input_html: { class: "inputs-product" },
    label: "Precio oferta" %>
    <%= f.input :discount, input_html: { class: "inputs-product" },
    label: "Aplicar precio oferta" %>
    <%= f.input :unit_type, input_html: { class: "inputs-product" },
    label: "Tipo de unidad (unidad, kilo, etc.)" %>
    <%= f.input :quantity_stock, input_html: { class: "inputs-product" },
    label: "Stock disponible" %>
    <%= f.input :featured, input_html: { class: "inputs-product" },
    label: "Producto destacado" %>
    <%= f.input :active, default: true, input_html: { class: "inputs-product" },
    label: "Producto activo" %>
    <%= f.association :categories, as: :check_boxes, input_html: { class: "inputs-product" },
    label: "Categorías" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true,class: "inputs-product" },
    label: "Fotografías" %>
  </div>
  <div class="dropdown-divider"></div>
  <div class="text-center d-flex align-items-center justify-content-center mb-4 pt-2">
    <%= f.button :submit, "Guardar", class: "btn boton-primario mx-1" %>
    <%= link_to  "Volver", request.referrer, class: "btn boton-secundario mx-1" %>
  </div>
  <% end %>
</div>

app/views/products/_product_card.html.erb
<% @products.each do |product| %>
  <% if product.active %>
    <div class="m-1">
      <div class="product-card">
        <%= link_to(product_path(product)) do %>
          <% if product.photos.attached? %>
            <% product.photos.first(1).each do |photo| %>
              <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill, alt: "#{product.name}", class: "image-card" %>
            <% end %>
          <% else %>
            <%= image_tag "no_product_image.png", height: 150, width: 200, crop: :fill, alt: "#{product.name}", class: "image-card" %>
          <% end %>
          <p class="product-store-name pl-2 pt-2 pb-1"><%= product.store.name %></p>
          <p class="product-name pl-2 pb-1">
            <%= product.name %>
            <% if product.featured %>
              <i class="fas fa-star"></i>
            <% end %>
          </p>

        <% if product.discount %>
        <div class="discount-tag">
          <p><%= ((product.price - product.discount_price) * 100) / product.price %>% Ahorro</p>
        </div>
        <div class="d-flex align-items-center">
          <p class="product-price discount pl-2">$<%= product.discount_price %></p>
          <p class="product-price-discount pl-2">$<%= product.price %></p>
        </div>

        <% else %>
          <p class="product-price pl-2">$<%= product.price %></p>
          <% end %>
        <% end %>
        <div class="form-quantity-product d-flex flex-column align-items-center">
          <%= simple_form_for(@cart_item, remote: true) do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <div class="d-flex align-items-center">
              <%= f.button :button, "-", class: "signo-btn minus", onclick: "document.getElementById('#{product.id}').value = parseInt(document.getElementById('#{product.id}').value) - 1; return false " %>
              <%= f.number_field :quantity, value: 1, label: false, class: "quantity-product my-2 text-center", id: product.id %>
              <%= f.button :button, "+", class: "signo-btn plus", onclick: "document.getElementById('#{product.id}').value = parseInt(document.getElementById('#{product.id}').value) + 1; return false" %>
            </div>
              <%= f.submit "Añadir al carrito", class: "btn boton-primario my-2" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end -%>

app/views/products/edit.html.erb
<h1 class="card-title text-center mt-5">Editar Producto</h1>
<div class="new-product-form mt-5 mb-5">
  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<div class="container my-5">

  <h1 class="card-title text-center">Productos</h1>
  <div class="d-flex flex-column align-items-center">

  <div class="products-store mt-5 justify-content-start mx-4">
    <%= render "product_card" %>
  </div>

  <div class="pagination m-2 p-2 align-self-center ">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
  </div>

  </div>
</div>

app/views/products/new.html.erb
<h1 class="card-title text-center mt-5">Agregar Producto</h1>
<div class="new-store-form mt-5">
  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<div class="product-background d-flex align-items-center">
  <div class="container">
    <div class="product-show-card d-flex align-items-center py-5 px-4">
      <div id="productCarousel" class="carousel slide" data-ride="carousel" style="height: 300px; width: 350px">
        <% if @product.photos.attached? %>
          <div class="carousel-inner mx-4">
            <% @product.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= "active" if index == 0 %> mx-6">
                <%= cl_image_tag photo.key, height: 300, width: 300, crop: :fill, alt: @product.name, class: "d-block" %>
              </div>
            <% end %>
          </div>
          <% if @product.photos.count > 1 %>
            <a class="carousel-control-prev" href="#productCarousel" role="button" data-slide="prev">
              <span class="fa fa-chevron-circle-left text-secondary" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#productCarousel" role="button" data-slide="next">
              <span class="fa fa-chevron-circle-right text-secondary" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          <% end %>
        <% else %>
          <%= image_tag "no_product_image.png", alt: "@product.name", class: "product-image-show mr-5 grow-1" %>
        <% end %>
      </div>

      <div class="grow-2">
        <%= link_to store_path(@product.store) do %>
          <p class="product-store-show"><%= @product.store.name %> </p>
        <% end %>
        <p class="product-name-show"><%= @product.name %></p>
        <p class="sku">SKU: <%= @product.sku %></p>

        <% if @product.discount %>
          <div class="discount-tag-show">
            <p><%= ((@product.price - @product.discount_price) * 100) / @product.price %>% Ahorro</p>
          </div>
          <div class="d-flex align-items-center">
            <p class="product-price discount mr-2">$<%= @product.discount_price %></p>
            <p class="product-price-discount">$<%= @product.price %></p>
            <p class="ml-1 product-price-type">/<%= @product.unit_type %></p>
          </div>
        <% else %>
          <p class="product-price mt-2">$<%= @product.price %> / <%= @product.unit_type %></p>
        <% end -%>
        <p class="sku mt-3">Cantidad:</p>
          <%= simple_form_for(@cart_item, remote: true) do |f| %>
        <div class="d-flex align-items-center">
            <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.button :button, "-", class: "signo-btn minus",onclick: "document.getElementById('#{@product.id}').value = parseInt(document.getElementById('#{@product.id}').value) - 1; return false " %>
              <%= f.number_field :quantity, label: false, value: 1,id: @product.id, class: "my-2 text-center input-quantity-show"%>
              <%= f.button :button, "+", class: "signo-btn plus", onclick: "document.getElementById('#{@product.id}').value = parseInt(document.getElementById('#{@product.id}').value) + 1; return false" %>
            <%= f.submit "Añadir al carrito", class: "btn boton-primario my-2 ml-3" %>

            <% if policy(@product.store).edit? %>
                <%= link_to edit_product_path(@product.id), class: "ml-4" do %>
                  <i class="fas fa-pen danger"></i>
                <% end %>
            <% end %>
        </div>
          <% end %>

        <div class="order-divider mt-3"></div>
        <div class="d-flex mt-4">
          <p class="sku mr-1 categories">Categorías:</p>
          <% @product.categories.each do |category| %>
            <%= link_to category_path(category) do %>
              <p class="sku"><%= category.name %></p>
            <% end %>
          <% end -%>
        </div>

      </div>

      <div class="feature-background-show grow-1 ml-5 py-2 pl-4">
        <div class="feature my-4">
          <%= image_tag "rocket.png", alt: "Cohete", class: "img-feature mr-2" %>
          <div class="">
            <p class="feature-title show">Envíos gratis</p>
            <p class="feature-subtitle show-subtitle">En compras mayores a $50.000</p>
          </div>
        </div>

        <div class="feature my-4">
          <%= image_tag "devolucion.png", alt: "Devolución", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title show">Devoluciones</p>
            <p class="feature-subtitle show-subtitle">Antes de las 24 horas</p>
          </div>
        </div>

        <div class="feature my-4">
          <%= image_tag "seguridad.png", alt: "Seguridad", class: "img-feature mr-2" %>
          <div>
            <p class="feature-title show">Pagos 100% Seguros</p>
            <p class="feature-subtitle show-subtitle">Pagos seguros garantizados</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container d-flex mt-5 mb-5 ">
  <div class="feature-background-show p-4 width">
    <div><p>Descripción</p></div>
    <div class="order-divider my-3"></div>
    <p>Comentarios de la tienda</p>
    <div class="order-divider my-3"></div>
    <p>Información del vendedor</p>
  </div>
    <p class="mt-3 pl-5"><%= @product.description %></p>
</div>